# Generated by Django 2.2.7 on 2019-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='imagen', verbose_name='Imagen')),
                ('botonurl', models.CharField(max_length=200, verbose_name='Url_boton')),
                ('imagenurl', models.CharField(max_length=200, verbose_name='Url_imagen')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('updateada', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
